### PR TITLE
RTR type and RTR packet fixes

### PR DESCRIPTION
**Pull request by gregjoyce**
Pick only a single RTR type if multiples are presented.

Signed-off-by: Greg Joyce <greg@opengridcomputing.com>

### CODE REVIEW

**Comment by gregjoyce** [comment]
RTR negotiation.

Signed-off-by: Greg Joyce greg@opengridcomputing.com

**Comment by larrystevenwise** [comment]
Hey Bernard, these two commits fix siw-cxgb4 interop problems and should be pulled in.  Thanks!

**Comment by larrystevenwise** [comment]
The chelsio implementation doesn't like stag 0 on the wire.  So setting it to non zero for the RTR avoid interop problems.  I can look into if the chelsio issue is a SW or FW, but it would be nice to have this code interoperate before going upstream :)

**Comment by larrystevenwise** [comment]
I'm checking with Chelsio on the 0stag issue.  I recall the RFCs were ambiguous, with one section saying ignore stag/to validation for 0B tagged messages, and yet another saying stag 0 should never be put on the wire.  I'll go rfc reading... :)

**Comment by BernardMetzler** [comment]
Thank you Greg. All in now.

**Pull request closed without merging**
